# Generated by Django 4.1.1 on 2022-09-15 14:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('surname', models.CharField(max_length=200, verbose_name='Surname')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('home', models.CharField(help_text='Enter your home location as -,-. (Ex. 12, 45)', max_length=7, verbose_name='Home Location')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='Start Time')),
                ('start_point', models.CharField(help_text='Enter your start location as -,-. (Ex. 12, 45)', max_length=7, verbose_name='Start Location')),
                ('end_point', models.CharField(help_text='Enter your end location as -,-. (Ex. 12, 45)', max_length=7, verbose_name='End Location')),
                ('total_distance', models.FloatField(verbose_name='Total Distance')),
                ('passenger_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.passenger')),
            ],
        ),
    ]
